name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dotfiles
        run: |
          cat <<-EOS > .env
          VAR_1=val_1
          VAR_2=val_2
          EOS
      - name: test
        run: |
          eval "$(./bin/shenv init -)"
          shenv
          [[ "$VAL_1" == "val_1" ]]
          [[ "$VAL_2" == "val_2" ]]
  test-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dotfiles
        run: |
          cat <<-EOS > .env
          VAR_1=val_1
          VAR_2=val_2
          EOS
          echo 'VAR_2=val_x' > .env.development
      - name: test
        run: |
          eval "$(./bin/shenv init -)"
          shenv .env .env.development
          [[ "$VAL_1" == "val_1" ]]
          [[ "$VAL_2" == "val_x" ]]
