name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |-
          cat <<-EOS > .env
          VAR_1=val_1
          VAR_2=val_2
          EOS
      - run: ./bin/shenv init -
      - run: eval "$(./bin/shenv init -)"
      - run: shenv
      - run: >-
          [[ "$VAL_1" == "val_1" ]] &&
          [[ "$VAL_2" == "val_2" ]]
  test-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |-
          cat <<-EOS > .env
          VAR_1=val_1
          VAR_2=val_2
          EOS
      - run: echo 'VAR_2=val_x' > .env.development
      - run: ./bin/shenv init -
      - run: eval "$(./bin/shenv init -)"
      - run: shenv .env .env.development
      - run: >-
          [[ "$VAL_1" == "val_1" ]] &&
          [[ "$VAL_2" == "val_x" ]]
