name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          cp .env.development .env
          eval "$(./bin/shenv init -)"
          shenv
          echo "VAL_1: $VAL_1"
          echo "VAL_2: $VAL_2"
          # [[ "$VAL_1" == "val_1" ]]
          # [[ "$VAL_2" == "val_2" ]]
  test-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          eval "$(./bin/shenv init -)"
          shenv .env.development .env.test
          echo "VAL_1: $VAL_1"
          echo "VAL_2: $VAL_2"
          # [[ "$VAL_1" == "val_1" ]]
          # [[ "$VAL_2" == "val_x" ]]
